function [y1,y2,y3]=Set_PosSpCtrPara()%p是必要的参数
%12,13,14
PosSpCtrParax.Kp=0.5;
PosSpCtrParax.Ki=0.05;
PosSpCtrParax.Kd=0.3;

PosSpCtrParay.Kp=0.5;
PosSpCtrParay.Ki=0.05;
PosSpCtrParay.Kd=0.3;

PosSpCtrParaz.Kp=0.2;
PosSpCtrParaz.Ki=0.05;
PosSpCtrParaz.Kd=0.3;
%4
PosSpCtrParax.Expect=0;
PosSpCtrParay.Expect=0;
PosSpCtrParaz.Expect=0;

PosSpCtrParax.Real=0;
PosSpCtrParay.Real=0;
PosSpCtrParaz.Real=0;
%1
PosSpCtrParax.ErrorLimitFlag=0;
PosSpCtrParay.ErrorLimitFlag=0;
PosSpCtrParaz.ErrorLimitFlag=0;
%2
PosSpCtrParax.ErrorInterLimitFlag=0;
PosSpCtrParay.ErrorInterLimitFlag=0;
PosSpCtrParaz.ErrorInterLimitFlag=0;
%3
PosSpCtrParax.InterLeaveLimitFlag=0;
PosSpCtrParay.InterLeaveLimitFlag=0;
PosSpCtrParaz.InterLeaveLimitFlag=0;
%5
PosSpCtrParax.Feedback=0;
PosSpCtrParay.Feedback=0;
PosSpCtrParaz.Feedback=0;
%6
PosSpCtrParax.Error=0;
PosSpCtrParay.Error=0;
PosSpCtrParaz.Error=0;
%7
PosSpCtrParax.LastError=0;
PosSpCtrParay.LastError=0;
PosSpCtrParaz.LastError=0;
%8
PosSpCtrParax.ErrorLimitValue=0;
PosSpCtrParay.ErrorLimitValue=0;
PosSpCtrParaz.LastError=0;
%9
PosSpCtrParax.ErrorInterLeaveValue=0;
PosSpCtrParay.ErrorInterLeaveValue=0;
PosSpCtrParaz.ErrorInterLeaveValue=0;
%10
PosSpCtrParax.ErrorInterValue=0;
PosSpCtrParay.ErrorInterValue=0;
PosSpCtrParaz.ErrorInterValue=0;
%10
PosSpCtrParax.ErrorInterValue=0;
PosSpCtrParay.ErrorInterValue=0;
PosSpCtrParaz.ErrorInterValue=0;
%11
PosSpCtrParax.ErrorInterLimitValue=0;
PosSpCtrParay.ErrorInterLimitValue=0;
PosSpCtrParaz.ErrorInterLimitValue=0;
PosSpCtrParaz.ErrorInterValue=0;
%15
PosSpCtrParax.TotalOutput=0;
PosSpCtrParay.TotalOutput=0;
PosSpCtrParaz.TotalOutput=0;
%16
PosSpCtrParax.LastTotalOutput=0;
PosSpCtrParay.LastTotalOutput=0;
PosSpCtrParaz.LastTotalOutput=0;
%17
PosSpCtrParax.LimitTotalOutput=0;
PosSpCtrParay.LimitTotalOutput=0;
PosSpCtrParaz.LimitTotalOutput=0;

y1=PosSpCtrParax;
y2=PosSpCtrParay;
y3=PosSpCtrParaz;