function [y1,y2,y3]=Set_PosCtrPara()%p是必要的参数
%12,13,14
PosCtrParax.Kp=0.5;
PosCtrParax.Ki=0.05;
PosCtrParax.Kd=0.3;

PosCtrParay.Kp=0.5;
PosCtrParay.Ki=0.05;
PosCtrParay.Kd=0.3;

PosCtrParaz.Kp=0.2;
PosCtrParaz.Ki=0.05;
PosCtrParaz.Kd=0.3;
%4
PosCtrParax.Expect=0;
PosCtrParay.Expect=0;
PosCtrParaz.Expect=0;

PosCtrParax.Real=0;
PosCtrParay.Real=0;
PosCtrParaz.Real=0;
%1
PosCtrParax.ErrorLimitFlag=0;
PosCtrParay.ErrorLimitFlag=0;
PosCtrParaz.ErrorLimitFlag=0;
%2
PosCtrParax.ErrorInterLimitFlag=0;
PosCtrParay.ErrorInterLimitFlag=0;
PosCtrParaz.ErrorInterLimitFlag=0;
%3
PosCtrParax.InterLeaveLimitFlag=0;
PosCtrParay.InterLeaveLimitFlag=0;
PosCtrParaz.InterLeaveLimitFlag=0;
%5
PosCtrParax.Feedback=0;
PosCtrParay.Feedback=0;
PosCtrParaz.Feedback=0;
%6
PosCtrParax.Error=0;
PosCtrParay.Error=0;
PosCtrParaz.Error=0;
%7
PosCtrParax.LastError=0;
PosCtrParay.LastError=0;
PosCtrParaz.LastError=0;
%8
PosCtrParax.ErrorLimitValue=0;
PosCtrParay.ErrorLimitValue=0;
PosCtrParaz.LastError=0;
%9
PosCtrParax.ErrorInterLeaveValue=0;
PosCtrParay.ErrorInterLeaveValue=0;
PosCtrParaz.ErrorInterLeaveValue=0;
%10
PosCtrParax.ErrorInterValue=0;
PosCtrParay.ErrorInterValue=0;
PosCtrParaz.ErrorInterValue=0;
%10
PosCtrParax.ErrorInterValue=0;
PosCtrParay.ErrorInterValue=0;
PosCtrParaz.ErrorInterValue=0;
%11
PosCtrParax.ErrorInterLimitValue=0;
PosCtrParay.ErrorInterLimitValue=0;
PosCtrParaz.ErrorInterLimitValue=0;
PosCtrParaz.ErrorInterValue=0;
%15
PosCtrParax.TotalOutput=0;
PosCtrParay.TotalOutput=0;
PosCtrParaz.TotalOutput=0;
%16
PosCtrParax.LastTotalOutput=0;
PosCtrParay.LastTotalOutput=0;
PosCtrParaz.LastTotalOutput=0;
%17
PosCtrParax.LimitTotalOutput=0;
PosCtrParay.LimitTotalOutput=0;
PosCtrParaz.LimitTotalOutput=0;

y1=PosCtrParax;
y2=PosCtrParay;
y3=PosCtrParaz;
